# Generated by Django 3.2.9 on 2023-11-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petal2', '0004_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialproduct',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
